DROP TABLE public.customer CASCADE;
DROP TABLE public.car CASCADE;
DROP TABLE public.registration CASCADE;
DROP TABLE public.parkingspot CASCADE;
DROP TABLE public.tarif CASCADE;
DROP TABLE public.mark CASCADE;
DROP TABLE public.parkingticket CASCADE;
DROP TABLE public.typepayment CASCADE;
DROP TABLE public.typespot CASCADE;